import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { parse } from "yaml";
import { describe, expect, it } from "vitest";
import { Checker, buildValeFiles, exportVale, loadRules, readmeTable } from "../src/index.js";

const ruleSet = loadRules();
const { files, skipped } = buildValeFiles(ruleSet);

describe("export-vale", () => {
  it("keeps the file names circe-docs already uses", () => {
    const names = files.map((f) => f.path);
    for (const n of ["EmDash.yml", "Hedges.yml", "Intensifiers.yml", "TrailingContrast.yml", "InferiorBaseline.yml"]) expect(names).toContain(n);
  });

  it("splits a rule with mixed token severities into two files", () => {
    const main = files.find((f) => f.path === "TrailingContrast.yml")!;
    const warn = files.find((f) => f.path === "TrailingContrastWarning.yml")!;
    expect(main.level).toBe("error");
    expect(main.tokens).toEqual(["rather than", "instead of", "not only", "not just"]);
    expect(warn.level).toBe("warning");
    expect(warn.tokens).toContain("go beyond");
  });

  it("skips heuristic-only rules and leaves nothing without an RE2-safe pattern", () => {
    expect(files.some((f) => f.rule.id === "CES-C-002")).toBe(false);
    expect(skipped).toEqual([]);
    for (const f of files) for (const t of f.tokens) expect(t, `${f.path}: ${t}`).not.toMatch(/\(\?<?[=!]/);
  });

  it("produces valid YAML with Vale's existence fields and %s messages", () => {
    for (const f of files) {
      const doc = parse(f.content) as Record<string, unknown>;
      expect(doc.extends).toBe("existence");
      expect(doc.level).toBe(f.level);
      expect(String(doc.message)).toMatch(new RegExp(`^${f.rule.id}: `));
      if (f.rule.message.includes("{match}")) expect(String(doc.message)).toContain("%s");
      expect(doc.tokens).toEqual(f.tokens);
      expect(f.content).toContain("Generated by `circe-mcp export-vale`");
    }
  });

  it("carries the exception and the inline-comment instructions into the file comment", () => {
    const main = files.find((f) => f.path === "TrailingContrast.yml")!;
    expect(main.content).toContain("Exception: Keep a contrast");
    expect(main.content).toContain("<!-- vale Circe.TrailingContrast = NO -->");
  });

  it("writes the files and prints a README table with one row per file", () => {
    const dir = mkdtempSync(join(tmpdir(), "circe-vale-"));
    const result = exportVale(ruleSet, dir);
    for (const f of result.files) expect(existsSync(join(dir, f.path))).toBe(true);
    const table = readmeTable(ruleSet);
    expect(table.split("\n")).toHaveLength(files.length + 2);
    expect(table).toContain("| CES-C-008 No trailing contrast clauses | `TrailingContrast.yml` | error |");
  });
});

const valeBin = process.env.VALE_BIN ?? (existsSync("../bin/vale") ? resolve("../bin/vale") : "vale");
const haveVale = (() => {
  try {
    execFileSync(valeBin, ["--version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
})();

describe.skipIf(!haveVale)("Vale agrees with the exported styles", () => {
  it("flags the same rules on the same lines as the server", () => {
    const dir = mkdtempSync(join(tmpdir(), "circe-vale-run-"));
    exportVale(ruleSet, join(dir, "styles", "Circe"));
    writeFileSync(join(dir, ".vale.ini"), "StylesPath = styles\nMinAlertLevel = suggestion\n\n[*.md]\nBasedOnStyles = Circe\n");
    const text = [
      "The release shipped on time — a rare occurrence.",
      "",
      "It is actually faster, and genuinely so, rather than slower.",
      "",
      "Prior experience backs this up: the pattern holds in practice.",
      "",
      "<!-- vale Circe.TrailingContrast = NO -->",
      "Moved from MS Access to SQL Server rather than rewriting.",
      "<!-- vale Circe.TrailingContrast = YES -->",
    ].join("\n");
    writeFileSync(join(dir, "sample.md"), text);
    let out = "";
    try {
      out = execFileSync(valeBin, ["--output=JSON", "sample.md"], { cwd: dir, encoding: "utf8" });
    } catch (e) {
      out = (e as { stdout: string }).stdout; // Vale exits 1 on errors
    }
    const alerts = (JSON.parse(out) as Record<string, Array<{ Check: string; Line: number }>>)["sample.md"] ?? [];
    const fromVale = alerts.map((a) => `${a.Check.replace(/^Circe\./, "").replace(/(Warning|Suggestion)$/, "")}@${a.Line}`).sort();

    const checker = new Checker(ruleSet);
    const fromServer = checker
      .check(text)
      .violations.flatMap((v) => [v, ...(v.related ?? [])].map((x) => `${(checker.rule(x.ruleId)!.vale as { name: string }).name}@${v.line}`))
      .sort();
    expect(fromVale).toEqual(fromServer);
  });
});
