/**
 * Generates Vale style files from the rules file (D1). One file per rule; a
 * second file with a level suffix when a rule's tokens carry mixed severities
 * (D5). Heuristic-only rules and tokens marked `vale: false` are skipped.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Rule, RuleSet, RuleToken, Severity } from "./types.js";
import { SEVERITY_ORDER } from "./types.js";

export interface ValeFile {
  name: string;
  path: string;
  rule: Rule;
  level: Severity;
  tokens: string[];
  content: string;
}

export interface ExportResult {
  files: ValeFile[];
  skipped: string[];
}

const LEVEL_SUFFIX: Record<Severity, string> = { error: "", warning: "Warning", suggestion: "Suggestion" };

export function buildValeFiles(ruleSet: RuleSet): ExportResult {
  const files: ValeFile[] = [];
  const skipped: string[] = [];

  for (const rule of ruleSet.rules) {
    if (rule.vale === false || !rule.tokens?.length) continue;
    const baseName = rule.vale.name;
    const groups = new Map<Severity, string[]>();
    for (const token of rule.tokens) {
      const pattern = valePattern(token);
      if (pattern === null) {
        skipped.push(`${rule.id}: ${token.phrase ?? token.regex} (no RE2-safe pattern)`);
        continue;
      }
      const level = token.severity ?? rule.severity;
      if (!groups.has(level)) groups.set(level, []);
      groups.get(level)!.push(pattern);
    }
    const levels = [...groups.keys()].sort((a, b) => SEVERITY_ORDER[a] - SEVERITY_ORDER[b]);
    levels.forEach((level, i) => {
      const name = i === 0 ? baseName : `${baseName}${LEVEL_SUFFIX[level]}`;
      const tokens = groups.get(level)!;
      files.push({ name, path: `${name}.yml`, rule, level, tokens, content: render(rule, name, level, tokens, i > 0) });
    });
  }
  return { files, skipped };
}

/** Writes the files into a directory such as circe-docs/styles/Circe. */
export function exportVale(ruleSet: RuleSet, dir: string): ExportResult {
  const result = buildValeFiles(ruleSet);
  mkdirSync(dir, { recursive: true });
  for (const f of result.files) writeFileSync(join(dir, f.path), f.content, "utf8");
  return result;
}

/** Markdown rows for a README rule table, matching the circe-docs README layout. */
export function readmeTable(ruleSet: RuleSet): string {
  const { files } = buildValeFiles(ruleSet);
  const lines = ["| Rule | File | Level | Catches |", "|---|---|---|---|"];
  for (const f of files) {
    const catches = f.tokens.map((t) => `\`${t.replace(/\\s\$/, "").replace(/\\b/g, "")}\``).join(", ");
    lines.push(`| ${f.rule.id} ${f.rule.name} | \`${f.path}\` | ${f.level} | ${catches} |`);
  }
  return lines.join("\n");
}

function valePattern(token: RuleToken): string | null {
  if (token.vale === false) return null;
  if (typeof token.vale === "string") return token.vale;
  if (token.phrase !== undefined) {
    const escaped = token.phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    // Vale wraps tokens in \b...\b. A phrase that ends in punctuation needs a
    // following space to give the boundary something to match.
    return /[\p{L}\p{N}]$/u.test(token.phrase) ? escaped : `${escaped}\\s`;
  }
  if (token.regex !== undefined && !/\(\?<?[=!]/.test(token.regex)) return token.regex;
  return null;
}

function render(rule: Rule, name: string, level: Severity, tokens: string[], secondary: boolean): string {
  const effect = level === "error" ? "fails CI" : "reports without failing CI";
  const out: string[] = [];
  out.push(`# ${rule.id}. ${rule.rating}; this file runs at ${level} and ${effect}.`);
  if (secondary) out.push(`# Lower-confidence tokens of ${rule.id}. The high-confidence tokens are in ${rule.vale ? rule.vale.name : ""}.yml.`);
  out.push(...wrap(rule.description, "# "));
  if (rule.exception) {
    out.push("#");
    out.push(...wrap(`Exception: ${rule.exception}`, "# "));
    out.push("# Silence a justified exception with an inline comment:");
    out.push(`#   <!-- vale Circe.${name} = NO -->`);
    out.push("#   ...sentence...");
    out.push(`#   <!-- vale Circe.${name} = YES -->`);
  }
  out.push("#");
  out.push("# Generated by `circe-mcp export-vale` from rules/ces.yaml. Edit the rules file, not this one.");
  out.push("extends: existence");
  out.push(`message: ${yamlString(`${rule.id}: ${rule.message.replace("{match}", "%s")}`)}`);
  out.push(`level: ${level}`);
  out.push("ignorecase: true");
  if (rule.vale && rule.vale.nonword) out.push("nonword: true");
  out.push("tokens:");
  for (const t of tokens) out.push(`  - '${t.replace(/'/g, "''")}'`);
  return out.join("\n") + "\n";
}

function wrap(text: string, prefix: string, width = 78): string[] {
  const lines: string[] = [];
  let line = "";
  for (const word of text.split(/\s+/)) {
    if ((line + " " + word).trim().length > width - prefix.length) {
      lines.push(prefix + line.trim());
      line = "";
    }
    line += " " + word;
  }
  if (line.trim()) lines.push(prefix + line.trim());
  return lines;
}

function yamlString(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
